#ifndef SYSTEMTRAYICON_GLOBAL_H
#define SYSTEMTRAYICON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SYSTEMTRAYICON_LIBRARY)
#  define SYSTEMTRAYICONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SYSTEMTRAYICONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SYSTEMTRAYICON_GLOBAL_H
