#ifndef SPLASHSCREEN_GLOBAL_H
#define SPLASHSCREEN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SPLASHSCREEN_LIBRARY)
#  define SPLASHSCREENSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SPLASHSCREENSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SPLASHSCREEN_GLOBAL_H
